export const USER_LOGGED_IN = 'USER_LOGGED_IN'
export const USER_LOGGED_IN_SUCCESS = 'USER_LOGGED_IN_SUCCESS'
export const USER_LOGGED_IN_FAILURE = 'USER_LOGGED_IN_FAILURE'
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'
export const USER_LOGGED_OUT_SUCCESS = 'USER_LOOGED_OUT_SUCCESS'
export const USER_LOGGED_OUT_FAILURE = 'USER_LOGGED_OUT_FAILURE'
export const USER_CADASTRO = 'USER_CADASTRO'
export const USER_CADASTRO_SUCCESS = 'USER_CADASTRO_SUCCESS'
export const USER_CADASTRO_FAILURE = 'USER_CADASTRO_FAILURE'
export const USER_UPDATE_DATA = 'USER_UPDATE_DATA'
export const USER_LOAD_DATA_SUCCESS = 'USER_LOAD_DATA_SUCESS'
export const USER_LOAD_DATA = 'USER_LOAD_DATA'
export const USER_LOAD_DATA_FAILURE = 'USER_LOAD_DATA_FAILURE'


export const PET_CADASTRO = 'PET_CADASTRO'
export const PET_DELETE = 'PET_DELETE'
export const PET_UPDATE = 'PET_UDATE'


export const INTERESSADOS_GET = 'INTERESSADOS_GET'
export const INTERESSADOS_DELETE = 'INTERESSADOS_DELETE'
export const INTERESSADOS_UPDATE = 'INTERESSADOS_UPDATE'
